// tool/build_dart_index.dart
//
// lib/ 配下の .dart ファイルを走査して、第一階層フォルダごとに JSON を分割出力します。
// 出力先: .dart-index/
//   - .dart-index/lib/<top-level>/index.json
//   - .dart-index/index.json  … カタログ（フォルダ一覧・件数・生成時刻）
//
// JSON にはファイルの相対パス、サイズ、行数、SHA1、内容(content)を含めます。
// ※ リポジトリが巨大な場合は必要に応じて content を削る/短縮する等で調整してください。

import 'dart:convert';
import 'dart:io';
import 'package:crypto/crypto.dart' show sha1;

void main(List<String> args) async {
  final libDir = Directory('lib');
  if (!await libDir.exists()) {
    stderr.writeln('lib/ が見つかりません。プロジェクト直下で実行してください。');
    exitCode = 1;
    return;
  }

  final outRoot = Directory('.dart-index');
  if (!await outRoot.exists()) {
    await outRoot.create(recursive: true);
  }

  // 収集: フォルダ => ファイル情報リスト
  final Map<String, List<Map<String, dynamic>>> buckets = {};

  final dartFiles = await _listDartFiles(libDir);
  for (final f in dartFiles) {
    final relPath = _relativePath(f.path.replaceAll('\\', '/'), base: 'lib');
    final topLevel = _topLevelBucket(relPath); // 例: "services" / "_root"
    final content = await f.readAsString();
    final stat = await f.stat();

    final lines = '\n'.allMatches(content).length + 1;
    final hash = sha1.convert(utf8.encode(content)).toString();

    final info = <String, dynamic>{
      'path': 'lib/$relPath',                // リポジトリ相対（lib/付き）
      'rel': relPath,                        // lib/からの相対
      'name': relPath.split('/').last,       // ファイル名
      'size': stat.size,                     // バイト
      'lines': lines,                        // 行数
      'sha1': hash,                          // 内容のハッシュ
      'content': content,                    // ファイル内容
    };

    buckets.putIfAbsent(topLevel, () => <Map<String, dynamic>>[]).add(info);
  }

  // 出力: フォルダごと
  final outCatalog = <Map<String, dynamic>>[];
  for (final entry in buckets.entries) {
    final folder = entry.key; // 例: "services" / "_root"
    // 並びを安定化（パス昇順）
    entry.value.sort((a, b) => (a['path'] as String).compareTo(b['path'] as String));

    final outDir = Directory('.dart-index/lib/$folder');
    await outDir.create(recursive: true);

    final jsonObj = {
      'folder': folder,
      'base': folder == '_root' ? 'lib' : 'lib/$folder',
      'generatedAt': DateTime.now().toUtc().toIso8601String() + 'Z',
      'count': entry.value.length,
      'files': entry.value,
    };

    final dst = File('${outDir.path}/index.json');
    await dst.writeAsString(const JsonEncoder.withIndent('  ').convert(jsonObj), encoding: utf8);

    outCatalog.add({
      'folder': folder,
      'base': folder == '_root' ? 'lib' : 'lib/$folder',
      'count': entry.value.length,
      'index': 'lib/$folder/index.json',
    });
  }

  // 出力: ルートのカタログ
  outCatalog.sort((a, b) => (a['folder'] as String).compareTo(b['folder'] as String));
  final root = {
    'folders': outCatalog,
    'generatedAt': DateTime.now().toUtc().toIso8601String() + 'Z',
    'note': 'Per-folder dart index generated by tool/build_dart_index.dart',
  };
  final rootFile = File('.dart-index/index.json');
  await rootFile.writeAsString(const JsonEncoder.withIndent('  ').convert(root), encoding: utf8);

  // 目視用ログ
  stdout.writeln('Generated ${outCatalog.length} folder indices under .dart-index/');
  for (final f in outCatalog) {
    stdout.writeln(' - ${f['index']} (${f['count']} files)');
  }
}

/// lib/ 配下の .dart ファイルを再帰的に列挙
Future<List<File>> _listDartFiles(Directory libDir) async {
  final out = <File>[];
  await for (final e in libDir.list(recursive: true, followLinks: false)) {
    if (e is File && e.path.endsWith('.dart')) {
      // .g.dart 等も拾いたくない場合はここで除外
      out.add(e);
    }
  }
  return out;
}

/// lib/ からの相対パスに変換（前提: absPath が lib/ を含む）
String _relativePath(String absPath, {required String base}) {
  final marker = '$base/';
  final idx = absPath.indexOf(marker);
  if (idx < 0) return absPath; // 想定外だが保険
  return absPath.substring(idx + marker.length);
}

/// 第一階層のバケット名を返す。lib/直下は "_root"
String _topLevelBucket(String relPath) {
  final parts = relPath.split('/');
  if (parts.isEmpty) return '_root';
  if (parts.length == 1) return '_root';
  return parts.first; // 例: services, screens, models, ...
}